# Define queue rules
queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"  # Ensure at least one approved review is present

# Define pull request rules
pull_request_rules:
  - name: Automerge to main with label 'automerge' and passing branch protection
    conditions:
      - "#approved-reviews-by>=1"      # Ensure at least one approved review is present
      - base=main                      # Ensure the target branch is 'main'
      - label=merge me daddy           # Ensure the PR has the 'merge me daddy' label
    actions:
      queue:
        name: default
        method: squash                # Squash commits before merging
        commit_message_template: |    # Template for the commit message
          {{ title }} (#{{ number }})
          {{ body }}

  - name: Backport patches to 'v0.0.2-alpha' branch
    conditions:
      - base=main                      # Ensure the target branch is 'main'
      - label=backport/v0.0.2-alpha    # Ensure the PR has the 'backport/v0.0.2-alpha' label
    actions:
      backport:
        branches:
          - release/v0.0.2-alpha      # Target branch for backporting
